= Big box
:sectnums:
:nofooter:
:toc: left

[blockquote, T-h2o]
____
A Big box is a generic word for say a "project".
____

== File hierachy

[graphviz, target=assets/framework, format=svg]
....
graph G {
  fontname="Helvetica,Arial,sans-serif"
  node [fontname="Helvetica,Arial,sans-serif"]
  edge [fontname="Helvetica,Arial,sans-serif"]
  layout=fdp
  e
  subgraph clusterA {
    a -- b;
    subgraph clusterC {
      C -- D;
    }
  }
  subgraph clusterB {
    d -- f;
  }
  d -- D;
  e -- clusterB;
  clusterC -- clusterB;
}
....

=== The program

inc:: Include, for headers files
src:: Source, for source code files
obj:: Objet, for compiled source code

=== The documentation

doc:: Documentation folder

=== The tester

test:: Contains all sources for testing the program

== Tools

=== Version control

git:: no need to say more

=== A source code formater

clang-format:: Clang format is a tool from `llvm` for formatting source files

== Markup language

[blockquote, Linus Torvalds]
____
Use https://asciidoc.org/[AsciiDoc] for document markup. Really.
It's actually readable by humans, easier to parse and way more flexible than XML.
____

=== HTML generator

[blockquote, Asciidoctor]
____
Convert AsciiDoc to HTML5
____

The tool is available into this docker https://hub.docker.com/r/asciidoctor/docker-asciidoctor[image]

. pull the image
+
[source, bash]
----
docker pull asciidoctor/docker-asciidoctor
----

. run the image with interactive mode
+
[source, bash]
----
docker run -it -v ${PWD}:/documents/ asciidoctor/docker-asciidoctor
----

== Makefile rules

all:: Compile the program
db:: Compile the program and launch a debugger on the program
format:: Run clang-format in each source files
doc:: Generate from AsciiDoc into html

== Workflow

An article on a git workflow https://gastaud.io/article/git-workflow/[git-workflow]
