= Big box
:sectnums:
:nofooter:
:toc: left

[blockquote, T-h2o]
____
A Big box is a generic word to say a "project".
____

== Framework

https://react.dev/[react]:: frontend
https://nestjs.com/[nestJS]:: backend
https://www.cypress.io/[cypress]:: test
https://www.figma.com/[figma]:: design close source application
https://penpot.app/[penpot]:: design open source web application

== File hierachy

Follow the most possible the standard of frameworks.

=== Documentations

docs:: Documentation folder with an `index.html` inside.

=== Testers

test:: Contains all sources for testing the project

== Tools

=== Version control

git:: an example of a git workflow https://gastaud.io/article/git-workflow/[git-workflow]

=== code formater

https://prettier.io/[prettier]:: code formatter for the web

=== Project tracking

https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects[GitHub project]:: A project tracking builtin of GitHub

=== plantUML

https://plantuml.com/[plantUML]:: From plain text to UML diagram

=== TypeScript Style Guide

https://google.github.io/styleguide/tsguide.html[Google Style Guide]:: The Google style guide for the TypeScript

=== Markup language

https://asciidoc.org/[AsciiDoc]:: It is clear as markdown and has more feature than markdown. Read https://asciidoctor.org/docs/what-is-asciidoc/[what is AsciiDoc].

== Plan of operation

. Create the repository and two main branches and set rules for them
+
* `main`
** require a pull request before merging
** require three approvals
** dismiss stale pull request approvals when new commits are pushed
** lock branch
** do not allow bypassing the above settings
* `stage`
** require a pull request before merging
** require three approvals
** dismiss stale pull request approvals when new commits are pushed
. Setup framework and docker
. Design the web application
. Develope feature after feature
